/**
 * This file will be generated by kysely-codegen.
 * Please do not edit it manually.
 * 
 * Run: npm run db:generate-customer-types
 */

import type { ColumnType, Generated, JSONColumnType } from "kysely";

// Placeholder - will be generated when customer schema is migrated
export interface DB {
  // Customer tables will be added here when generated
}